# Generated by Django 5.2 on 2026-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='verified', max_length=64, verbose_name='Іконка')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Фіча «Про нас»',
                'verbose_name_plural': 'Фічі «Про нас»',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('eyebrow', models.CharField(blank=True, max_length=128, verbose_name='Eyebrow')),
                ('lead', models.TextField(blank=True, verbose_name='Lead')),
                ('body', models.TextField(blank=True, verbose_name='Тіло (HTML)')),
                ('header_image', models.ImageField(blank=True, upload_to='pages/', verbose_name='Зображення заголовку')),
                ('header_image_url', models.CharField(blank=True, max_length=512, verbose_name='URL зображення (fallback)')),
            ],
            options={
                'verbose_name': 'Сторінка контенту',
                'verbose_name_plural': 'Сторінки контенту',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Питання FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(choices=[('hero', 'Hero'), ('about', 'Про нас (превʼю)'), ('services', 'Послуги (превʼю)'), ('portfolio', 'Портфоліо (превʼю)'), ('cta', 'CTA / форма')], unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=64, verbose_name='Назва в адмінці')),
                ('is_visible', models.BooleanField(default=True, help_text='Вимкніть, щоб повністю приховати цей блок на сайті.', verbose_name='Показувати на головній')),
                ('eyebrow', models.CharField(blank=True, max_length=128, verbose_name='Підпис над заголовком')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('title_line1', models.CharField(blank=True, max_length=64, verbose_name='Заголовок рядок 1')),
                ('title_line2', models.CharField(blank=True, max_length=64, verbose_name='Заголовок рядок 2')),
                ('title_accent', models.CharField(blank=True, max_length=64, verbose_name='Акцентний рядок')),
                ('lead', models.TextField(blank=True, verbose_name='Лід / опис')),
                ('text_1', models.TextField(blank=True, verbose_name='Текст 1')),
                ('text_2', models.TextField(blank=True, verbose_name='Текст 2')),
                ('checklist', models.TextField(blank=True, help_text='Кожен пункт з нового рядка', verbose_name='Чеклист')),
                ('cta_text', models.CharField(blank=True, max_length=64, verbose_name='Кнопка 1 — текст')),
                ('cta_url', models.CharField(blank=True, max_length=255, verbose_name='Кнопка 1 — посилання')),
                ('cta_secondary_text', models.CharField(blank=True, max_length=64, verbose_name='Кнопка 2 — текст')),
                ('cta_secondary_url', models.CharField(blank=True, max_length=255, verbose_name='Кнопка 2 — посилання')),
                ('form_title', models.CharField(blank=True, max_length=128, verbose_name='Заголовок форми')),
                ('form_hint', models.CharField(blank=True, max_length=255, verbose_name='Підказка форми')),
                ('image', models.ImageField(blank=True, help_text='Hero / about media. Рекомендовано JPG/WebP до 2 МБ', upload_to='blocks/', verbose_name='Зображення')),
                ('image_url', models.CharField(blank=True, help_text='Наприклад /static/images/hero_roof_premium.png', max_length=512, verbose_name='URL зображення (якщо без upload)')),
                ('link_text', models.CharField(blank=True, max_length=64, verbose_name='Текст посилання')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='URL посилання')),
                ('stat_1_label', models.CharField(blank=True, max_length=64, verbose_name='Стат 1 — підпис')),
                ('stat_2_label', models.CharField(blank=True, max_length=64, verbose_name='Стат 2 — підпис')),
                ('stat_3_label', models.CharField(blank=True, max_length=64, verbose_name='Стат 3 — підпис')),
            ],
            options={
                'verbose_name': 'Блок головної',
                'verbose_name_plural': 'Блоки головної',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Елемент marquee',
                'verbose_name_plural': 'Marquee',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Назва')),
                ('city', models.SlugField(max_length=64, verbose_name='Місто (slug)')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/', verbose_name='Фото (upload)')),
                ('image_url', models.CharField(blank=True, help_text='Fallback, якщо немає upload', max_length=512, verbose_name='URL фото')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('date', models.CharField(blank=True, max_length=64, verbose_name='Дата')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='На головній')),
            ],
            options={
                'verbose_name': 'Робота портфоліо',
                'verbose_name_plural': 'Портфоліо',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Опис')),
                ('icon', models.CharField(default='roofing', max_length=64, verbose_name='Іконка (Material Symbol)')),
                ('variant', models.CharField(choices=[('accent', 'Accent'), ('dark', 'Dark')], default='accent', max_length=16, verbose_name='Варіант')),
                ('features', models.TextField(blank=True, help_text='Кожна з нового рядка', verbose_name='Особливості')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='На головній')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Покрівля під ключ', max_length=128, verbose_name='Назва сайту')),
                ('site_name_line1', models.CharField(default='Покрівля', max_length=64, verbose_name='Назва (рядок 1)')),
                ('site_name_line2', models.CharField(default='під ключ', max_length=64, verbose_name='Назва (рядок 2)')),
                ('owner', models.CharField(default='Юра', max_length=64, verbose_name='Власник')),
                ('location', models.CharField(default='Біла Церква, Київська обл.', max_length=255, verbose_name='Локація')),
                ('phone', models.CharField(default='096 409 66 12', max_length=32, verbose_name='Телефон')),
                ('phone_tel', models.CharField(default='+380964096612', max_length=32, verbose_name='Телефон (tel:)')),
                ('email', models.EmailField(default='pokrivlia.pid.kliuch@gmail.com', max_length=254, verbose_name='Email')),
                ('hours_weekdays', models.CharField(default='Пн – Пт: 08:00 – 20:00', max_length=128, verbose_name='Години (будні)')),
                ('hours_weekend', models.CharField(default='Сб – Нд: 09:00 – 18:00', max_length=128, verbose_name='Години (вихідні)')),
                ('stats_projects', models.CharField(default='400+', max_length=32, verbose_name='Статистика: проекти')),
                ('stats_experience', models.CharField(default='20+', max_length=32, verbose_name='Статистика: досвід')),
                ('stats_warranty', models.CharField(default='10', max_length=32, verbose_name='Статистика: гарантія')),
                ('callback_hint', models.CharField(default='Відповімо протягом дня у робочий час', max_length=255, verbose_name='Підказка форми')),
                ('material_brands', models.TextField(blank=True, default='Ruukki, Braas, Velux, Katepal, BRYZA, RAINWAY', help_text='Через кому', verbose_name='Бренди матеріалів')),
                ('meta_description', models.TextField(blank=True, default='Професійний монтаж покрівлі будь-якої складності. Скандинавська якість та безкомпромісна надійність.', verbose_name='SEO description')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='01', max_length=8, verbose_name='Номер')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Опис')),
                ('features', models.TextField(blank=True, help_text='Кожна з нового рядка', verbose_name='Особливості')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Чому ми',
                'verbose_name_plural': 'Чому ми',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
