# Generated by Django 5.2 on 2026-07-08 13:06

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cms_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marqueeitem',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Елемент стрічки', 'verbose_name_plural': 'Стрічка на головній'},
        ),
        migrations.AlterModelOptions(
            name='telegramconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Розмова в чаті', 'verbose_name_plural': 'Розмови в чаті'},
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Повідомлення чату', 'verbose_name_plural': 'Повідомлення чату'},
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст сторінки'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=128, verbose_name='Підпис над заголовком'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='lead',
            field=models.TextField(blank=True, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код сторінки'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='key',
            field=models.SlugField(choices=[('hero', 'Головний банер'), ('about', 'Про нас (превʼю)'), ('services', 'Послуги (превʼю)'), ('portfolio', 'Портфоліо (превʼю)'), ('cta', 'Форма зворотного звʼязку')], unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='variant',
            field=models.CharField(choices=[('accent', 'Акцент'), ('dark', 'Темний')], default='accent', max_length=16, verbose_name='Варіант'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True, default='Професійний монтаж покрівлі будь-якої складності. Скандинавська якість та безкомпромісна надійність.', verbose_name='Опис для пошуковиків (SEO)'),
        ),
        migrations.AlterField(
            model_name='telegramconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='telegramconversation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='telegramconversation',
            name='session_key',
            field=models.CharField(db_index=True, default=core.models.generate_session_key, max_length=6, unique=True, verbose_name='Код сесії'),
        ),
        migrations.AlterField(
            model_name='telegramconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='telegramconversation',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Ім'я відвідувача"),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.telegramconversation', verbose_name='Розмова'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='sender',
            field=models.CharField(choices=[('visitor', 'Відвідувач'), ('operator', 'Оператор')], max_length=20, verbose_name='Відправник'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID у Telegram'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
