# Generated by Django 5.2 on 2026-07-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_admin_ux_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'розмову в чаті', 'verbose_name_plural': 'Розмови в чаті'},
        ),
        migrations.AlterModelOptions(
            name='telegrammessage',
            options={'ordering': ['created_at'], 'verbose_name': 'повідомлення чату', 'verbose_name_plural': 'Повідомлення чату'},
        ),
    ]
