# Generated by Django 5.2 on 2026-07-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegram_verbose_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement', models.CharField(max_length=120, verbose_name='Населений пункт')),
                ('work_type', models.CharField(choices=[('new_roof', 'Монтаж нового даху'), ('recon_with_demolition', 'Реконструкція (з демонтажем старої покрівлі)'), ('recon_without_demolition', 'Реконструкція (без демонтажу)')], max_length=64, verbose_name='Тип робіт')),
                ('area', models.CharField(choices=[('up_to_100', 'до 100 м²'), ('100_200', '100–200 м²'), ('200_300', '200–300 м²'), ('over_300', 'більше 300 м²')], max_length=32, verbose_name='Площа даху')),
                ('floors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('over_3', 'більше 3')], max_length=16, verbose_name='Поверхів будівлі')),
                ('material', models.CharField(choices=[('metal_tile', 'Металочерепиця'), ('metal_profile', 'Металопрофіль'), ('bitumen_tile', 'Бітумна черепиця'), ('seam_roof', 'Фальцева покрівля'), ('ceramic_tile', 'Керамічна черепиця')], max_length=64, verbose_name='Покрівельний матеріал')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('source', models.CharField(blank=True, default='', max_length=64, verbose_name='Джерело')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'заявку на кошторис',
                'verbose_name_plural': 'Заявки на кошторис',
                'ordering': ['-created_at'],
            },
        ),
    ]
