"""Portfolio gallery data: cities and project photos."""

PORTFOLIO_FILTERS = [
    {'slug': 'all', 'label': 'Усі проекти'},
    {'slug': 'bilogorodka', 'label': 'Білогородка'},
    {'slug': 'bloshchentsi', 'label': 'Блощенці'},
    {'slug': 'borodyanka', 'label': 'Бородянка'},
    {'slug': 'gorenychi', 'label': 'Гореничі'},
    {'slug': 'karpaty', 'label': 'Карпати'},
    {'slug': 'kyiv', 'label': 'Київ'},
    {'slug': 'mizhrichchya', 'label': 'Міжріччя'},
    {'slug': 'novi-petrivtsi', 'label': 'Нові Петрівці'},
    {'slug': 'obukhiv', 'label': 'Обухів'},
    {'slug': 'pogreby', 'label': 'Погреби'},
    {'slug': 'ruda', 'label': 'Руда'},
    {'slug': 'terezine', 'label': 'Терезіне'},
    {'slug': 'khotyanivka', 'label': 'Хотянівка'},
]

PORTFOLIO_ITEMS = [
    {'id': 1, 'title': 'Білогородка', 'city': 'bilogorodka', 'image': '/static/images/portfolio/bilogorodka/1809.webp', 'alt': 'Покрівельні роботи, Білогородка'},
    {'id': 2, 'title': 'Білогородка', 'city': 'bilogorodka', 'image': '/static/images/portfolio/bilogorodka/1810.webp', 'alt': 'Покрівельні роботи, Білогородка'},
    {'id': 3, 'title': 'Білогородка', 'city': 'bilogorodka', 'image': '/static/images/portfolio/bilogorodka/IMG_20260612_180148.webp', 'alt': 'Покрівельні роботи, Білогородка'},
    {'id': 4, 'title': 'Блощенці', 'city': 'bloshchentsi', 'image': '/static/images/portfolio/bloshchentsi/IMG_20240411_144136.webp', 'alt': 'Покрівельні роботи, Блощенці'},
    {'id': 5, 'title': 'Блощенці', 'city': 'bloshchentsi', 'image': '/static/images/portfolio/bloshchentsi/IMG_20240411_144158.webp', 'alt': 'Покрівельні роботи, Блощенці'},
    {'id': 6, 'title': 'Блощенці', 'city': 'bloshchentsi', 'image': '/static/images/portfolio/bloshchentsi/IMG_20240411_144223.webp', 'alt': 'Покрівельні роботи, Блощенці'},
    {'id': 7, 'title': 'Бородянка', 'city': 'borodyanka', 'image': '/static/images/portfolio/borodyanka/IMG_20250901_184749.webp', 'alt': 'Покрівельні роботи, Бородянка'},
    {'id': 8, 'title': 'Бородянка', 'city': 'borodyanka', 'image': '/static/images/portfolio/borodyanka/IMG_20250903_113635.webp', 'alt': 'Покрівельні роботи, Бородянка'},
    {'id': 9, 'title': 'Бородянка', 'city': 'borodyanka', 'image': '/static/images/portfolio/borodyanka/IMG_20250903_113651.webp', 'alt': 'Покрівельні роботи, Бородянка'},
    {'id': 10, 'title': 'Бородянка', 'city': 'borodyanka', 'image': '/static/images/portfolio/borodyanka/IMG_20250903_113745.webp', 'alt': 'Покрівельні роботи, Бородянка'},
    {'id': 11, 'title': 'Бородянка', 'city': 'borodyanka', 'image': '/static/images/portfolio/borodyanka/IMG_20251002_104309.webp', 'alt': 'Покрівельні роботи, Бородянка'},
    {'id': 12, 'title': 'Бородянка', 'city': 'borodyanka', 'image': '/static/images/portfolio/borodyanka/IMG_20251002_104401.webp', 'alt': 'Покрівельні роботи, Бородянка'},
    {'id': 13, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20240807_130226.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 14, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20240807_130241.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 15, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20240830_120041.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 16, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20241004_125511.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 17, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20241004_125543.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 18, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20241004_125605.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 19, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20241004_125641.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 20, 'title': 'Гореничі', 'city': 'gorenychi', 'image': '/static/images/portfolio/gorenychi/IMG_20241004_125714.webp', 'alt': 'Покрівельні роботи, Гореничі'},
    {'id': 21, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG-20260618-WA0002.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 22, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG-20260618-WA0006.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 23, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG-20260618-WA0010.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 24, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG-20260618-WA0011.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 25, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG-20260618-WA0014.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 26, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG-20260618-WA0019.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 27, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG_20240524_074256.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 28, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG_20240603_195359.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 29, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG_20240618_191912.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 30, 'title': 'Карпати', 'city': 'karpaty', 'image': '/static/images/portfolio/karpaty/IMG_20240618_191922.webp', 'alt': 'Покрівельні роботи, Карпати'},
    {'id': 31, 'title': 'Київ', 'city': 'kyiv', 'image': '/static/images/portfolio/kyiv/IMG_20251226_142944.webp', 'alt': 'Покрівельні роботи, Київ'},
    {'id': 32, 'title': 'Київ', 'city': 'kyiv', 'image': '/static/images/portfolio/kyiv/IMG_20251226_143151.webp', 'alt': 'Покрівельні роботи, Київ'},
    {'id': 33, 'title': 'Київ', 'city': 'kyiv', 'image': '/static/images/portfolio/kyiv/IMG_20260417_120312.webp', 'alt': 'Покрівельні роботи, Київ'},
    {'id': 34, 'title': 'Київ', 'city': 'kyiv', 'image': '/static/images/portfolio/kyiv/IMG_20260417_120321.webp', 'alt': 'Покрівельні роботи, Київ'},
    {'id': 35, 'title': 'Київ', 'city': 'kyiv', 'image': '/static/images/portfolio/kyiv/IMG_20260417_121014.webp', 'alt': 'Покрівельні роботи, Київ'},
    {'id': 36, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0001.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 37, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0003.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 38, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0004.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 39, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0005.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 40, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0007.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 41, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0013.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 42, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0041.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 43, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0042.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 44, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0052.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 45, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0053.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 46, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0054.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 47, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0055.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 48, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0056.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 49, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0057.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 50, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0059.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 51, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0061.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 52, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0063.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 53, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0064.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 54, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0065.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 55, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0066.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 56, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0067.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 57, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0068.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 58, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0069.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 59, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0070.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 60, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0071.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 61, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0072.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 62, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0073.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 63, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0076.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 64, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0077.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 65, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0079.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 66, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG-20260618-WA0080.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 67, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG_20260615_101253.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 68, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG_20260615_102334.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 69, 'title': 'Міжріччя', 'city': 'mizhrichchya', 'image': '/static/images/portfolio/mizhrichchya/IMG_20260615_102413.webp', 'alt': 'Покрівельні роботи, Міжріччя'},
    {'id': 70, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0029.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 71, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0030.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 72, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0032.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 73, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0033.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 74, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0034.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 75, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0044________.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 76, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0048.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 77, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0049.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 78, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG-20260618-WA0050.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 79, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20230830_084805.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 80, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20250605_152737.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 81, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20250605_152842.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 82, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20250605_152855.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 83, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20260615_100950.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 84, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20260615_101336.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 85, 'title': 'Нові Петрівці', 'city': 'novi-petrivtsi', 'image': '/static/images/portfolio/novi-petrivtsi/IMG_20260615_102509.webp', 'alt': 'Покрівельні роботи, Нові Петрівці'},
    {'id': 86, 'title': 'Обухів', 'city': 'obukhiv', 'image': '/static/images/portfolio/obukhiv/IMG_20260620_132738.webp', 'alt': 'Покрівельні роботи, Обухів'},
    {'id': 87, 'title': 'Обухів', 'city': 'obukhiv', 'image': '/static/images/portfolio/obukhiv/IMG_20260620_132812.webp', 'alt': 'Покрівельні роботи, Обухів'},
    {'id': 88, 'title': 'Погреби', 'city': 'pogreby', 'image': '/static/images/portfolio/pogreby/IMG_20230509_205238.webp', 'alt': 'Покрівельні роботи, Погреби'},
    {'id': 89, 'title': 'Погреби', 'city': 'pogreby', 'image': '/static/images/portfolio/pogreby/IMG_20230611_120407.webp', 'alt': 'Покрівельні роботи, Погреби'},
    {'id': 90, 'title': 'Погреби', 'city': 'pogreby', 'image': '/static/images/portfolio/pogreby/IMG_20230611_120529.webp', 'alt': 'Покрівельні роботи, Погреби'},
    {'id': 91, 'title': 'Погреби', 'city': 'pogreby', 'image': '/static/images/portfolio/pogreby/IMG_20230611_120613.webp', 'alt': 'Покрівельні роботи, Погреби'},
    {'id': 92, 'title': 'Руда', 'city': 'ruda', 'image': '/static/images/portfolio/ruda/IMG_20260615_105836_093.webp', 'alt': 'Покрівельні роботи, Руда'},
    {'id': 93, 'title': 'Руда', 'city': 'ruda', 'image': '/static/images/portfolio/ruda/IMG_20260615_105836_716.webp', 'alt': 'Покрівельні роботи, Руда'},
    {'id': 94, 'title': 'Руда', 'city': 'ruda', 'image': '/static/images/portfolio/ruda/IMG_20260615_105836_787.webp', 'alt': 'Покрівельні роботи, Руда'},
    {'id': 95, 'title': 'Руда', 'city': 'ruda', 'image': '/static/images/portfolio/ruda/IMG_20260615_105836_976.webp', 'alt': 'Покрівельні роботи, Руда'},
    {'id': 96, 'title': 'Терезіне', 'city': 'terezine', 'image': '/static/images/portfolio/terezine/IMG_20230413_143958.webp', 'alt': 'Покрівельні роботи, Терезіне'},
    {'id': 97, 'title': 'Терезіне', 'city': 'terezine', 'image': '/static/images/portfolio/terezine/IMG_20230413_144002.webp', 'alt': 'Покрівельні роботи, Терезіне'},
    {'id': 98, 'title': 'Терезіне', 'city': 'terezine', 'image': '/static/images/portfolio/terezine/IMG_20230413_144020.webp', 'alt': 'Покрівельні роботи, Терезіне'},
    {'id': 99, 'title': 'Терезіне', 'city': 'terezine', 'image': '/static/images/portfolio/terezine/IMG_20230413_144030.webp', 'alt': 'Покрівельні роботи, Терезіне'},
    {'id': 100, 'title': 'Хотянівка', 'city': 'khotyanivka', 'image': '/static/images/portfolio/khotyanivka/IMG-20260618-WA0036.webp', 'alt': 'Покрівельні роботи, Хотянівка'},
    {'id': 101, 'title': 'Хотянівка', 'city': 'khotyanivka', 'image': '/static/images/portfolio/khotyanivka/IMG-20260618-WA0062.webp', 'alt': 'Покрівельні роботи, Хотянівка'},
    {'id': 102, 'title': 'Хотянівка', 'city': 'khotyanivka', 'image': '/static/images/portfolio/khotyanivka/IMG_20260615_101506.webp', 'alt': 'Покрівельні роботи, Хотянівка'},
]

HOME_PORTFOLIO_PREVIEW = [
    {
        'title': 'Карпати',
        'city': 'karpaty',
        'image': '/static/images/portfolio/home-preview/IMG-20260618-WA0002.webp',
        'alt': 'Покрівельні роботи, Карпати',
    },
    {
        'title': 'Міжріччя',
        'city': 'mizhrichchya',
        'image': '/static/images/portfolio/home-preview/IMG-20260618-WA0005.webp',
        'alt': 'Покрівельні роботи, Міжріччя',
    },
    {
        'title': 'Нові Петрівці',
        'city': 'novi-petrivtsi',
        'image': '/static/images/portfolio/home-preview/IMG-20260618-WA0029.webp',
        'alt': 'Покрівельні роботи, Нові Петрівці',
    },
    {
        'title': 'Міжріччя',
        'city': 'mizhrichchya',
        'image': '/static/images/portfolio/home-preview/IMG-20260618-WA0052.webp',
        'alt': 'Покрівельні роботи, Міжріччя',
    },
]

PORTFOLIO_CITY_SLUGS = {item['slug'] for item in PORTFOLIO_FILTERS if item['slug'] != 'all'}


def get_portfolio_city_label(city_slug):
    for item in PORTFOLIO_FILTERS:
        if item['slug'] == city_slug:
            return item['label']
    return city_slug


def get_portfolio_items_for_city(city_slug):
    return [item for item in PORTFOLIO_ITEMS if item['city'] == city_slug]
